version: '3'
services:
  neo4j:
    image: neo4j:3.2.3
    ports:
      - "7474:7474"
      - "7687:7687"
    volumes:
      - ./dbs/n4j/data:/data
  graphql:
    # need privileged mode to be able to run debugger (remove for production!)
    privileged: true
    depends_on:
      - neo4j
    build:
      context: ./
      dockerfile: Dockerfile
      args:
        debug: 0
        hotswap: 0
    image: go/graphql
    container_name: go-graphql
    ports:
      - "9000:8080"
      - "2345:2345"
    # use volumes only for development otherwise copy in the source
    volumes:
      - ./:/go/src/graphql-server
